config/routes.rb
Rails.application.routes.draw do
  if Rails.env.production?
    devise_for :users, controllers: { registrations: 'registrations' }
  else
    devise_for :users
  end

  get '/rss' => 'home#rss', as: :rss_feed, defaults: { format: 'rss' }
  get '/contacts' => 'home#contacts', as: :contacts

  resources :albums
  resources :projects
  resources :images
  resources :photos, only: :destroy
  resources :settings

  root to: 'home#index'
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  load_and_authorize_resource :setting

  def index
  end

  def show
  end

  def new
  end

  def create
    if @setting.save
      redirect_to settings_path
    else
      render :edit
    end
  end

  def edit
  end

  def update
    if @setting.update_attributes(setting_params)
      redirect_to setting_path(@setting)
    else
      render :edit
    end
  end

  def destroy
    @setting.destroy
    redirect_to settings_path
  end

private

  def setting_params
    params.require(:setting).permit(
      :env, :host, :title, :copyright_holder, :contact_text,
      :contact_text_ua, :facebook_account, :instagram_account, :flickr_user_id, :linkedin_account,
      :description, :google_analytics_account
    )
  end
end

app/views/settings/_form.html.erb
<%= simple_form_for @setting, html: {class: 'form-inline'} do |f| %>
  <%= f.input :env %>
  <%= f.input :host, label: 'Site domain' %>
  <%= f.input :title, label: 'Site title', input_html: {class: 'input-xxlarge'} %>
  <%= f.input :copyright_holder %>
  <%= f.input :contact_text, input_html: {rows: 10, cols: 40, class: 'input-xxlarge'} %>
  <%= f.input :contact_text_ua, input_html: {rows: 10, cols: 40, class: 'input-xxlarge'} %>
  <h3>External profiles</h3>
  <%= f.input :facebook_account %>
  <%= f.input :instagram_account %>
  <%= f.input :flickr_user_id %>
  <%= f.input :linkedin_account, input_html: {class: 'input-xxlarge'} %>
  <h3>Technical stuff</h3>
  <%= f.input :description, input_html: {class: 'input-xxlarge'} %>
  <%= f.input :google_analytics_account %>

  <%= f.button :submit, class: 'btn-primary' %>
<% end %>

app/views/settings/edit.html.erb
<h1>
  <%= link_to 'View', setting_path(@setting), class: 'btn btn-primary' if @setting.persisted? %>
  Edit <%= @setting.env %> Setting
</h1>

<%= render 'form' %>

app/views/settings/index.html.erb
<h1>
  <%= link_to 'New Setting', new_setting_path, class: 'btn btn-primary' %>

  Settings
  <small>list of all setting</small>
</h1>

<table class="table">
  <thead>
  <tr>
    <th>Environment</th>
    <th>Values</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @settings.each do |setting| %>
    <tr>
      <td>
        <strong><%= setting.env %></strong>
      </td>
      <td>
        <table class="table">
          <tr>
            <th>Param</th>
            <th>Value</th>
          </tr>
          <% setting.attributes.each do |attr| %>
            <tr>
              <td><%= attr[0] %></td>
              <td>
                <% if %w[contact_text contact_text_ua].include?(attr[0]) %>
                  <%= highlight_links(attr[1]).html_safe %>
                <% else %>
                  <%= attr[1] %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </table>
      </td>
      <td>
        <p>
          <%= link_to 'Edit', edit_setting_path(setting), class: 'btn btn-primary' %>
          <%= link_to 'Delete', setting_path(setting), class: 'btn', method: 'delete', data: {confirm: 'Delete setting ?'} %>
        </p>
      </td>
    </tr>
  <% end %>
  </tbody>
  <thead>
  <tr>
    <th>Environment</th>
    <th>Values</th>
    <th>Actions</th>
  </tr>
  </thead>
</table>

app/views/settings/new.html.erb
<h1>New Setting
  <small>add one</small>
</h1>

<%= render 'form' %>

app/views/settings/show.html.erb
<h1>
  <%= link_to 'Edit', edit_setting_path(@setting), class: 'btn btn-primary' if @setting.persisted? %>
  <%= @setting.env.capitalize %> Setting
</h1>

<table class="table">
  <tr>
    <th>Param</th>
    <th>Value</th>
  </tr>
  <% @setting.attributes.each do |attr| %>
    <tr>
      <td><%= attr[0] %></td>
      <td>
        <% if %w[contact_text contact_text_ua].include?(attr[0]) %>
          <%= highlight_links(attr[1]).html_safe %>
        <% else %>
          <%= attr[1] %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>