config/routes.rb
Rails.application.routes.draw do
  if Rails.env.production?
    devise_for :users, controllers: { registrations: 'registrations' }
  else
    devise_for :users
  end

  get '/rss' => 'home#rss', as: :rss_feed, defaults: { format: 'rss' }
  get '/contacts' => 'home#contacts', as: :contacts

  resources :albums
  resources :projects
  resources :images
  resources :photos, only: :destroy
  resources :settings

  root to: 'home#index'
end

app/models/project.rb
require 'portfolio/rss_record_touch'

class Project < ActiveRecord::Base
  include Portfolio::RssRecordTouch

  self.inheritance_column = nil

  has_many :photos, as: :owner, dependent: :destroy

  TYPES = %w[project publication]

  validates :title, presence: true
  validates :type, inclusion: { in: TYPES }

  accepts_nested_attributes_for :photos, allow_destroy: true, reject_if: proc { |a| !a.has_key?('id') && !a.has_key?('asset') }

  scope :recent, -> {
    includes(:photos).
      where(Project.arel_table[:created_at].gt(Time.now - 1.day).or(
              Photo.arel_table[:created_at].gt(Time.now - 1.day)))
  }

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  # Get first cover photo of a project
  # Returns {Photo}
  def cover_photo
    self.photos.where(is_cover: true).ordered.first || self.photos.ordered.first
  end

  def is_recent?
    Project.where(id: self.id).recent.exists?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource :project

  def index
    @projects = @projects.order('weight DESC')
    @q = @projects.search(params[:q])
    @projects = @q.result
    @projects = @projects.page(params[:page])
  end

  def show
  end

  def new
    @project.photos.build
  end

  def create
    @project.weight = begin (Project.order('weight DESC').first.weight + 1) rescue 0 end if @project.weight == 0
    if @project.save
      redirect_to edit_project_path(@project)
    else
      render :edit
    end
  end

  def edit
    @project.photos.build
  end

  def update
    if @project.update_attributes(project_params)
      redirect_to edit_project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    old_type = @project.type
    @project.destroy
    redirect_to projects_path(q: { type_eq: old_type })
  end

private

  def project_params
    params.require(:project).permit(
      :type, :title, :title_ua, :is_published, :description, :description_ua,
      :weight, :info, :info_ua, { photos_attributes: [:id, :asset, :asset_cache, :desc, :desc_ua, :is_cover, :weight] }
    )
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for @project,
                    as: :project,
                    url: (@project.new_record? ? projects_path : project_path(@project)),
                    html: {class: 'form-inline'} do |f| %>
  <%= f.input :type, as: :select, collection: Project::TYPES, required: true, include_blank: false %>
  <%= f.input :title, input_html: {class: 'input-xxlarge'} %>
  <%= f.input :title_ua, input_html: {class: 'input-xxlarge'} %>
  <%= f.input :info, input_html: {rows: 4, cols: 40, class: 'input-xxlarge'} %>
  <%= f.input :info_ua, input_html: {rows: 4, cols: 40, class: 'input-xxlarge'} %>
  <%= f.input :description, input_html: {rows: 8, cols: 40, class: 'input-xxlarge'} %>
  <%= f.input :description_ua, input_html: {rows: 8, cols: 40, class: 'input-xxlarge'} %>
  <%= f.input :is_published, as: :boolean %>
  <%= f.input :weight %>

  <%= f.button :submit, class: 'btn-primary', value: "#{@project.new_record? ? 'New' : 'Update'} #{@project.type == 'publication' ? 'Publication' : 'Project'}" %>

  <h3><%= I18n.t 'site.photos_title' %> <small>added after Project is created</small></h3>

  <ul class="thumbnails">
    <% if @project.persisted? %>
      <%= f.simple_fields_for :photos do |pf| %>
        <li class="span12">
          <div class="thumbnail">
            <% if pf.object && pf.object.asset? %>
              <div class="control-group">
                <div class="controls">
                  <%= link_to image_tag(pf.object.asset.url(:span2)), pf.object.asset.url(:big) %>
                </div>
              </div>
            <% else %>
              <h3><%= I18n.t 'site.new_photo' %></h3>
            <% end %>

            <%= pf.input :asset, as: :file %>
            <%= pf.input :asset_cache, as: :hidden %>
            <%= pf.input :desc, input_html: {rows: 2, cols: 40, class: 'input-xxlarge'} %>
            <%= pf.input :desc_ua, input_html: {rows: 2, cols: 40, class: 'input-xxlarge'} %>
            <%= pf.input :is_cover, as: :boolean %>
            <%= pf.input :weight %>

            <% if pf.object.persisted? %>
              <%= link_to (I18n.t 'site.delete'), photo_path(pf.object), class: 'btn', method: 'delete', data: {confirm: 'Delete photo?'} %>
            <% end %>
          </div>
        </li>
      <% end %>

      <%= f.button :submit, class: 'btn-primary', value: "#{@project.new_record? ? 'New' : 'Update'} #{@project.type == 'publication' ? 'Publication' : 'Project'}" %>
    <% end %>
  </ul>

<% end %>

app/views/projects/_index_admin.html.erb
<h1>
  <%= link_to "New #{params[:q] && params[:q][:type_eq] == 'publication' ? 'Publication' : 'Project'}", new_project_path, class: 'btn btn-primary' %>

  <%= params[:q] && params[:q][:type_eq] == 'publication' ? 'Publications' : 'Projects' %>
  <small>list of all <%= params[:q] && params[:q][:type_eq] == 'publication' ? 'publications' : 'projects' %></small>
</h1>

<%= paginate @projects %>

<table class="table">
  <thead>
  <tr>
    <th><%= sort_link @q, :id %></th>
    <th>Picture</th>
    <th>Type</th>
    <th>About</th>
    <th><%= sort_link @q, :weight %></th>
    <th><%= sort_link @q, :created_at %></th>
    <th><%= sort_link @q, :is_published %></th>
    <th>Photos</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @projects.each do |project| %>
    <tr>
      <td>
        <%= link_to project.id, project_path(project) %>
      </td>
      <td>
        <% if project.cover_photo %>
          <%= link_to(project_path(project), class: 'thumbnail span2') do
            image_tag(project.cover_photo.asset.url(:span2))
          end %>
        <% end %>
      </td>
      <td>
        <%= project.type %>
      </td>
      <td>
        <p><%= link_to get_local_value(I18n.locale, {en: project.title, ua: project.title_ua}), project_path(project) %></p>
        <p><%= highlight_links(get_local_value(I18n.locale, {en: project.info, ua: project.info_ua})).html_safe %></p>
      </td>
      <td>
        <%= project.weight %>
      </td>
      <td>
        <%= project.created_at.strftime('%d %b %Y') %>
      </td>
      <td>
        <%= project.is_published? ? 'yes' : 'no' %>
      </td>
      <td>
        <%= project.photos.count %>
      </td>
      <td>
        <p>
          <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-primary' %>
          <%= link_to 'Delete', project_path(project), class: 'btn', method: 'delete', data: {confirm: 'Delete project ?'} %>
        </p>
      </td>
    </tr>
  <% end %>
  </tbody>
  <thead>
  <tr>
    <th><%= sort_link @q, :id %></th>
    <th>Picture</th>
    <th>Type</th>
    <th>About</th>
    <th><%= sort_link @q, :weight %></th>
    <th><%= sort_link @q, :created_at %></th>
    <th><%= sort_link @q, :is_published %></th>
    <th>Photos</th>
    <th>Actions</th>
  </tr>
  </thead>
</table>

<%= paginate @projects %>

app/views/projects/_index_user.html.erb
<% if @projects.empty? %>
  No projects yet
<% end %>

<%= paginate @projects %>

<ul class="thumbnails">
  <% @projects.each do |project| %>
    <li class="span12">
      <h4>
        <%= link_to project_url(project) do %>
          <% if project.is_recent? %>
            <i class="unread"></i>
          <% end %>
          <%= get_local_value(I18n.locale, {en: project.title, ua: project.title_ua}) %>
        <% end %>
        <small><%= (I18n.t 'activerecord.models.project').downcase %></small>
      </h4>

      <div class="row">
        <div class="span3">
          <% if project.cover_photo %>
            <%= link_to(project_path(project), class: 'thumbnail span2') do
              image_tag(project.cover_photo.asset.url(:span2))
            end %>
          <% end %>
        </div>
        <div class="span9">
          <p><%= highlight_links(get_local_value(I18n.locale, {en: project.info, ua: project.info_ua})).html_safe %></p>
        </div>
      </div>
    </li>
  <% end %>
</ul>

<%= paginate @projects %>

<%= render 'home/contacts_block' %>

app/views/projects/_project.rss.erb
<p><%= I18n.t 'activerecord.models.project' %> <%= link_to get_local_value(I18n.locale, {en: project.title, ua: project.title_ua}), project_url(project) %></p>

<p>
  <% if project.cover_photo %>
    <%= link_to(project_path(project), class: 'thumbnail span2') do
      image_tag(project.cover_photo.asset.url(:span2))
    end %>
  <% end %>
</p>

<p><%= highlight_links(get_local_value(I18n.locale, {en: project.description, ua: project.description_ua})).html_safe %></p>

app/views/projects/edit.html.erb
<h1>
  <%= link_to 'View', project_path(@project), class: 'btn btn-primary' if @project.persisted? %>
  Edit <%= @project.type == 'publication' ? 'Publication' : 'Project' %>
</h1>

<%= render 'form' %>

app/views/projects/index.html.erb
<%= render user_signed_in? ? 'index_admin' : 'index_user' %>

app/views/projects/new.html.erb
<h1>New Project
  <small>add one</small>
</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<% content_for(:title) { get_local_value(I18n.locale, {en: @project.title, ua: @project.title_ua}) } %>

<h1>
  <% if user_signed_in? %>
    <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-primary' %>
  <% end %>

  <%= get_local_value(I18n.locale, {en: @project.title, ua: @project.title_ua}) %>
  <small>project</small>
</h1>

<p><%= highlight_links(get_local_value(I18n.locale, {en: @project.description, ua: @project.description_ua})).html_safe %></p>

<%= render 'photos/gallery', photos: @project.photos.ordered %>

<%= render 'home/contacts_block' %>