config/routes.rb
Rails.application.routes.draw do
  if Rails.env.production?
    devise_for :users, controllers: { registrations: 'registrations' }
  else
    devise_for :users
  end

  get '/rss' => 'home#rss', as: :rss_feed, defaults: { format: 'rss' }
  get '/contacts' => 'home#contacts', as: :contacts

  resources :albums
  resources :projects
  resources :images
  resources :photos, only: :destroy
  resources :settings

  root to: 'home#index'
end

app/models/image.rb
require 'portfolio/rss_record_touch'

class Image < ActiveRecord::Base
  mount_uploader :asset, ImageUploader
  include Portfolio::RssRecordTouch

  before_save :update_values

  def extension_white_list
    %w(jpg jpeg gif png)
  end

  def store_dir
    'public/uploads'
  end

  DEFAULT_QUERY = 'title_or_desc_or_tags_cache_or_place_or_album_title_cont'
  TITLE_MIN = 4
  DESC_MIN = 15
  TAGS_MIN = 10

  belongs_to :album, touch: true
  has_many :image_tags
  has_many :tags, through: :image_tags

  validates_presence_of :album, :title

  scope :sorted, -> { order('images.published_at DESC, images.created_at DESC') }
  scope :published, -> { where('images.published_at IS NOT NULL') }
  scope :from_published_albums, -> { joins(:album).where('albums.is_published = ?', true) }

  def to_param
    "#{self.id}-#{self.title.parameterize}"
  end

  def published_at_checkbox
    self.published_at.present?
  end

  def published_at_checkbox=(val)
    self.published_at = set_time(self.published_at, val)
  end

  def tags_resolved
    self.tags.map(&:name) * ', '
  end

  def tags_resolved=(names)
    tags_arr = []
    names.split(', ').uniq.each do |name|
      tag = Tag.where(name: name.strip).first_or_create
      ImageTag.where(image: self, tag: tag).first_or_create
      tags_arr << tag
    end
    update_values
  end

private

  def update_values
    self.tags_cache = self.tags_resolved
  end

  def set_time(initial_value, checkbox_value)
    if checkbox_value == '1' && initial_value.blank?
      Time.now
    else
      (checkbox_value != '1') ? nil : initial_value
    end
  end

protected

  def is_published_changed?
    self.published_at_changed?
  end

  def is_published?
    self.published_at.present?
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  load_and_authorize_resource :image, except: [:show]
  load_resource :image, only: [:show]

  def index
    @q = Image.sorted.includes([:album]).search(params[:q])
    @images = @q.result
    @images = @images.page(params[:page])
  end

  def show
    unless @image.published_at.present? || user_signed_in?
      redirect_to root_path, alert: 'Image is not published yet'
    end
  end

  def create
    if @image.save
      redirect_to image_path(@image)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @image.update_attributes(image_params)
      redirect_to image_path(@image)
    else
      render :edit
    end
  end

  def new
  end

  def destroy
    @image.destroy
    redirect_to images_path
  end

private

  def image_params
    params.require(:image).permit(
      :asset, :asset_cache, :album_id, :title, :title_ua, :desc, :desc_ua, :place, :place_ua, :date,
      :updated_at, :published_at_checkbox, :tags, :tags_resolved,
      :image_width, :image_height
    )
  end
end

app/helpers/image_helper.rb
# encoding: UTF-8

module ImageHelper
  def check_title(image)
    get_notice(image.title, Image::TITLE_MIN, 'words')
  end

  def check_desc(image)
    get_notice(render_image_data(I18n.locale, image), Image::DESC_MIN, 'words')
  end

  def check_tags(image)
    get_notice(image.tags_resolved, Image::TAGS_MIN, 'tags')
  end

  private

  def get_notice(str, need_words, object_names)
    if str.scan(/\w+/u).size < need_words
      "<span class=\"label label-important\">need #{need_words} #{object_names}</span>".html_safe
    end
  end
end

app/views/images/_form.html.erb
<%= simple_form_for @image, html: { class: 'form-inline' } do |f| %>
  <div class="well">
    <% if f.object.asset? %>
      <div class="control-group">
        <div class="controls">
          <%= link_to image_tag(f.object.asset.url(:span2)), f.object.asset.url(:big) %>
        </div>
      </div>
    <% end %>
    <%= f.input :asset, as: :file, required: !f.object.asset? %>
    <%= f.input :asset_cache, as: :hidden %>
    <%= f.input :album_id, as: :select, collection: Album.all, required: true, include_blank: false %>
    <%= f.input :title, input_html: { class: 'input-xxlarge' } %>
    <%= f.input :title_ua, input_html: { class: 'input-xxlarge' } %>
    <%= f.input :desc, input_html: { rows: 2, cols: 40, class: 'input-xxlarge' }  %>
    <%= f.input :desc_ua, input_html: { rows: 2, cols: 40, class: 'input-xxlarge' }  %>
    <%= f.input :place, input_html: { class: 'input-xxlarge' } %>
    <%= f.input :place_ua, input_html: { class: 'input-xxlarge' } %>
    <%= f.input :date, as: :date, order: [:year] %>
    <%= f.input :tags_resolved, as: :text, input_html: { rows: 2, cols: 40, class: 'input-xxlarge' } %>
    <%= f.input :published_at_checkbox, as: :boolean, label: "#{I18n.t 'simple_form.labels.image.published'} #{@image.published_at.present? ? " #{@image.published_at.strftime('%H:%M %d/%m/%Y')}" : ''}" %>
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/images/_gallery.html.erb
<div class="thumbnail" style="padding-left: 22px;">
  <ul class="thumbnails">
    <% images.each do |image| %>
      <li class="span" style="margin-bottom:5px;margin-left:5px;">
        <%= link_to "#img#{image.id}", rel: 'group', title: get_local_value(I18n.locale, {en: image.title, ua: image.title_ua}) do
          image_tag(image.asset.url(:span2), alt: image.id)
        end %>
      </li>
    <% end %>

    <% if images.size == 0 %>
      <li class="span2">
        <h3><%= I18n.t 'site.no_images' %></h3>
      </li>
    <% end %>
  </ul>
</div>

<%= paginate images %>

<ul class="thumbnails">
  <% images.each do |image| %>
    <li class="span12">
      <a name="img<%= image.id %>"></a>

      <h2>
        <% if user_signed_in? %>
          <%= link_to 'Edit', edit_image_path(image), class: 'btn btn-primary' %>
        <% end %>

        <%= link_to get_local_value(I18n.locale, {en: image.title, ua: image.title_ua}), image_url(image) %>

        <% if user_signed_in? %>
          <%= check_title(image) %>
        <% end %>

        <small class="pull-right"><%= get_local_value(I18n.locale, {en: image.album.title, ua: image.album.title_ua}) %></small>
      </h2>

      <div class="thumbnail">
        <%= image_tag(image.asset.url(:big), alt: image.title, title: image.title) %>
      </div>

      <div class="row">
        <p></p>

        <div class="span11">
          <p class="pull-left">
            <%= highlight_links(render_image_data(I18n.locale, image)).html_safe %>
            <% if user_signed_in? %>
              <%= check_desc(image) %>
            <% end %>

            <% unless image.tags.empty? %>
              <br/>
              <% image.tags.map(&:name).each do |tag| %>
                <%= link_to "<i class=\"icon-tag icon-white\"> </i> #{tag}".html_safe, root_path(q: {anything_like: tag}), class: 'label' %>
              <% end %>

              <% if user_signed_in? %>
                <%= check_tags(image) %>
              <% end %>
            <% end %>
          </p>
        </div>
      </div>
      <hr>
    </li>
  <% end %>
</ul>

<%= paginate images %>

<div>
  <% get_tags_cloud(images).each do |tag, count| %>
    <%= link_to tag, root_path(q: {anything_like: tag}), {style: "font-size:#{(count * 50) + 50}%;"} %>
  <% end %>
</div>

app/views/images/_image.rss.erb
<div>
  <p>
    <strong><%= get_local_value(I18n.locale, {en: image.title, ua: image.title_ua}) %></strong>.
    <%= highlight_links(render_image_data(I18n.locale, image)).html_safe %>
  </p>
</div>
<div>
  <%= link_to image_url(image) do
        image_tag(image.asset.url(:span2), alt: image.id)
  end %>
</div>
<div>
  <%= I18n.t 'activerecord.models.album'%>: <%= link_to get_local_value(I18n.locale, {en: image.album.title, ua: image.album.title_ua}), album_url(image.album) %>
</div>

<% unless image.tags.empty? %>
  <div>
    <%= I18n.t 'site.tags' %>:
    <% image.tags.map(&:name).each do |tag| %>
      <%= link_to tag, root_url(q: {anything_like: tag}) %>
    <% end %>
  </div>
<% end %>

<div>
  <%= I18n.t 'site.all_images' %>:
  <%= link_to_if get_setting('flickr_user_id').present?, 'Flickr', "http://www.flickr.com/photos/#{get_setting('flickr_user_id')}/" %>
</div>

app/views/images/edit.html.erb
<h1>Edit Image <small>update content</small></h1>

<%= render 'form' %>

app/views/images/index.html.erb
<h1>
  <%= link_to 'New Image', new_image_path, class: 'btn btn-primary' %>
  Images
  <small>list of all images</small>
</h1>

<%= paginate @images %>

<table class="table">
  <thead>
    <tr>
      <th><%= sort_link @q, :id %></th>
      <th>Thumb</th>
      <th>Info</th>
      <th><%= sort_link @q, :created_at, 'Dates' %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td>
          <p>
            <%= link_to image.id, edit_image_path(image.id) %>
          </p>
          <p>
            <%= image.album.title %>
            <% unless image.album.is_published? %>
              <span class="label label-important">hidden</span>
            <% end %>
          </p>
        </td>
        <td>
          <%= link_to(edit_image_path(image.id), class: 'thumbnail span2') do
            image_tag(image.asset.url(:span2))
          end %>
          <p class="pagination-centered"><%= "#{image.image_width}x#{image.image_height}" %></p>
        <td>
          <p>
            <strong><%= image.title %></strong>
            <%= check_title(image) %>
          </p>
          <p>
            <%= render_image_data(I18n.locale, image) %>
            <%= check_desc(image) %>
          </p>
          <p>
            <%= image.tags_resolved %>
            <%= check_tags(image) %>
          </p>
        </td>
        <td>
          <p>
            <%= time_ago_in_words(image.created_at) %> ago
          </p>
          <p>
            <% if image.published_at.present? %>
              <span class="label label-success"><%= time_ago_in_words(image.published_at) %> ago</span>
            <% else %>
              <span class="label label-warning">not published yet</span>
              <span class="label label-important">once per 30 minutes</span>
            <% end %>
          </p>
        </td>
        <td>
          <p>
            <%= link_to 'Edit', edit_image_path(image), class: 'btn btn-primary' %>
          </p>
          <p>
            <%= link_to 'Delete', image_path(image), class: 'btn', method: 'delete', data: { confirm: 'Delete image?' } %>
          </p>
        </td>
      </tr>
    <% end %>
  </tbody>
  <thead>
    <tr>
      <th><%= sort_link @q, :id %></th>
      <th>Thumb</th>
      <th>Info</th>
      <th><%= sort_link @q, :created_at, 'Dates' %></th>
      <th>Actions</th>
    </tr>
  </thead>
</table>

<%= paginate @images %>

app/views/images/new.html.erb
<h1>New Image <small>add content</small></h1>

<%= render 'form' %>

app/views/images/show.html.erb
<% content_for(:title) { get_local_value(I18n.locale, {en: @image.title, ua: @image.title_ua}) } %>

<ul class="thumbnails">
  <li class="span12">
    <h2>
      <% if user_signed_in? %>
        <%= link_to 'Edit', edit_image_path(@image), class: 'btn btn-primary' %>
      <% end %>

      <%= get_local_value(I18n.locale, {en: @image.title, ua: @image.title_ua}) %>

      <% if user_signed_in? %>
        <%= check_title(@image) %>
      <% end %>

      <small class="pull-right"><%= get_local_value(I18n.locale, {en: @image.album.title, ua: @image.album.title_ua}) %></small>
    </h2>

    <div class="thumbnail">
      <%= image_tag(@image.asset.url(:big), alt: @image.id) %>
    </div>

    <div class="row">
      <p></p>
      <div class="span11">
        <p class="pull-left">
          <%= highlight_links(render_image_data(I18n.locale, @image)).html_safe %>
          <% if user_signed_in? %>
            <%= check_desc(@image) %>
          <% end %>

          <% unless @image.tags.empty? %>
            <br/>
            <% @image.tags.map(&:name).each do |tag| %>
              <%= link_to "<i class=\"icon-tag icon-white\"> </i> #{tag}".html_safe, root_path(q: {anything_like: tag}), class: 'label' %>
            <% end %>

            <% if user_signed_in? %>
              <%= check_tags(@image) %>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  </li>
</ul>

<%= render 'home/contacts_block' %>