config/routes.rb
Rails.application.routes.draw do
  if Rails.env.production?
    devise_for :users, controllers: { registrations: 'registrations' }
  else
    devise_for :users
  end

  get '/rss' => 'home#rss', as: :rss_feed, defaults: { format: 'rss' }
  get '/contacts' => 'home#contacts', as: :contacts

  resources :albums
  resources :projects
  resources :images
  resources :photos, only: :destroy
  resources :settings

  root to: 'home#index'
end

app/views/layouts/_admin_navigation.html.erb
<div class="nav-collapse collapse">
  <ul class="nav pull-left">
    <li class="<%= current_page?(images_path) ? 'active' : '' %>">
      <%= link_to (I18n.t 'site.images_title'), images_path %>
    </li>
    <li class="<%= current_page?(new_image_path) ? 'active' : '' %>">
      <%= link_to (I18n.t 'site.new_image'), new_image_path, class: 'bnt-mini btn-primary' %>
    </li>
    <li class="divider-vertical"></li>
    <li class="<%= current_page?(albums_path) ? 'active' : '' %>">
      <%= link_to (I18n.t 'site.albums_title'), albums_path(q: {s: 'weight desc'}) %>
    </li>
    <li class="divider-vertical"></li>
    <li class="<%= (current_page?(settings_path) || @setting) ? 'active' : '' %>">
      <%= link_to (I18n.t 'site.settings_title'), settings_path %>
    </li>
    <li class="divider-vertical"></li>
    <li class="<%= current_page?(edit_user_registration_path) ? 'active' : '' %>">
      <%= link_to (I18n.t 'site.edit_account'), edit_user_registration_path %>
    </li>
    <li class="divider-vertical"></li>
    <li class="<%= current_page?(edit_user_registration_path) ? 'active' : '' %>">
      <%= link_to 'Sign Out', destroy_user_session_path, method: 'delete' %>
    </li>
  </ul>
</div>

app/views/layouts/_navigation.html.erb
<%= link_to 'Portfolio', root_path, class: 'brand' %>
<div class="nav-collapse collapse">
  <ul class="nav pull-left">
    <% if get_setting('contact_text').present? %>
      <li class="<%= current_page?(contacts_path) ? 'active' : '' %>">
        <%= link_to (I18n.t 'site.contacts_title'), contacts_path %>
      </li>
    <% end %>

    <% if Project.where(type: 'publication', is_published: true).exists? %>
      <li class="<%= (current_page?(projects_path(q: { type_eq: 'publication' })) || (@project && @project.type == 'publication')) ? 'active' : '' %>">
        <%= link_to projects_path(q: { type_eq: 'publication' }) do %>
          <%= (I18n.t 'site.publications_title') %>
          <% if Project.recent.where(type: 'publication').exists? %>
            <i class="unread"></i>
          <% end %>
        <% end %>
      </li>
    <% end %>

    <li class="<%= (current_page?(projects_path) || current_page?(projects_path(q: { type_eq: 'project' })) || (@project && @project.type == 'project')) ? 'active' : '' %>">
      <%= link_to projects_path(q: { type_eq: 'project' }) do %>
          <%= (I18n.t 'site.projects_title') %>
          <% if Project.recent.where(type: 'project').exists? %>
              <i class="unread"></i>
          <% end %>
      <% end %>
    </li>

    <% Album.published.order(weight: :asc).includes([:images]).each do |album| %>
      <% if album.images.size > 0 %>
        <li class="<%= current_page?(album_path(album)) || (@image && @image.album == album) ? 'active' : '' %>">
          <%= link_to album_path(album) do %>
            <%= get_local_value(I18n.locale, {en: album.title, ua: album.title_ua}) %>
            <% if album.is_recent? %>
              <i class="unread"></i>
            <% end %>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

<div class="nav-collapse collapse">
  <ul class="nav pull-left">
    <li>
      <%= link_to rss_feed_url, target: '_blank' do
        image_tag 'rss.png'
      end %>
    </li>
    <% if get_setting('flickr_user_id').present? %>
      <li>
        <%= link_to "http://www.flickr.com/photos/#{get_setting('flickr_user_id')}/", target: '_blank' do
          image_tag 'flickr.png'
        end %>
      </li>
    <% end %>
    <% if get_setting('facebook_account').present? %>
      <li>
        <%= link_to "https://www.facebook.com/#{get_setting('facebook_account')}/", target: '_blank' do
          image_tag 'facebook.png'
        end %>
      </li>
    <% end %>
    <% if get_setting('instagram_account').present? %>
      <li>
        <%= link_to "https://instagram.com/#{get_setting('instagram_account')}/", target: '_blank' do
          image_tag 'instagram.png'
        end %>
      </li>
    <% end %>
    <% if get_setting('linkedin_account').present? %>
      <li>
        <%= link_to get_setting('linkedin_account'), target: '_blank' do
          image_tag 'linkedin.png'
        end %>
      </li>
    <% end %>
    <!--<li>
      <form class="navbar-search pull-right" method="get" action="/">
        <label>
          <input type="text" class="input-medium search-query" placeholder="<%= I18n.t 'site.search' %>" name="q[anything_like]" value="<%= params[:q][:anything_like] if params[:q] %>">
        </label>
      </form>
    </li>-->
  </ul>
</div>

<div class="nav-collapse collapse">
  <ul class="nav pull-left">
    <li>
      <%= link_to 'En', request.query_parameters.merge({locale: 'en'}) %>
    </li>
    <li>
      <%= link_to 'Ua', request.query_parameters.merge({locale: 'ua'}) %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      <% if content_for?(:title) %>
        <%= yield(:title) %> -
      <% end %>
      <%= get_setting('title') %>
    </title>
    <meta name="description" content="<%= get_setting('description') %>">
    <meta name="author" content="<%= get_setting('copyright_holder') %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <%= auto_discovery_link_tag(:rss, rss_feed_url) %>
    <meta name="google-site-verification" content="2p1oQQtDfNHzwqUHXfb6kESw_Tcvn8YFL7Rg-cvF6a8" />
  </head>
  <body>
    <% if Rails.env.production? && !current_user && get_setting('google_analytics_account').present? %>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', '<%= get_setting('google_analytics_account') %>', 'auto');
        ga('require', 'displayfeatures');
        ga('send', 'pageview');
      </script>
    <% end %>

    <header class="navbar navbar-fixed navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
        <% if user_signed_in? %>
          <div class="container">
            <%= render 'layouts/admin_navigation' %>
          </div>
        <% end %>
      </nav>
    </header>
    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span12">
            <% flash.each do |name, msg| %>
              <div class="alert alert-<%= name == :notice ? 'success' : 'error' %>">
                <a class="close" data-dismiss="alert">×</a>
                <%= msg %>
              </div>
            <% end %>
            <%= yield %>
          </div>
        </div>
        <br/>
        <footer class="footer">
          <p style="color: #808080">
            <small>
              Copyright © 2011-<%= Time.now.year %> <%= get_setting('copyright_holder') %>
              <br/>
              Except where otherwise noted, content on <a style="color: dimgray" href="<%= get_setting('host') %>"><%= get_setting('host') %></a> is licensed under a <a  style="color: dimgray" rel="nofollow" href="http://creativecommons.org/licenses/by-nc-nd/3.0/">Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License</a>.
              <br/>
              This site is based on <a  style="color: dimgray" href="https://github.com/rilian/portfolio" rel="nofollow">rilian/portfolio</a> engine.
            </small>
          </p>
        </footer>
      </div>
    </div>

    <%= javascript_include_tag 'application' %>
  </body>
</html>